### ISSUE TITLE
Error when running updateDefinitionsHandler

### ISSUE THREAD

**Issue by cloudstorydev** [XcooBee/serverless-antivirus#2]
Thanks for making this available. 

Deployed as lambda, but when involing the function got the following error:

  "errorType": "Error",
    "errorMessage": "Command failed: ./freshclam --config-file=freshclam.conf --datadir=/tmp/\n./freshclam: error while loading shared libraries: libprelude.so.28: cannot open shared object file: No such file or directory\n",
    "trace": [
        "Error: Command failed: ./freshclam --config-file=freshclam.conf --datadir=/tmp/",
        "./freshclam: error while loading shared libraries: libprelude.so.28: cannot open shared object file: No such file or directory",
        "",
        "    at checkExecSyncError (child_process.js:616:11)",
        "    at execSync (child_process.js:652:15)",
        "    at updateDefinitions (/var/task/clamav.js:107:5)",
        "    at Runtime.updateDefinitionsHandler [as handler] (/var/task/index.js:12:11)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"

**Comment by Bilal-S** [comment]
@vrabeshko can you take a look?

**Comment by Bilal-S** [comment]
Fixed with PR 
https://github.com/XcooBee/serverless-antivirus/pull/3

@cloudstorydev try to rebuild and let us know.

**Comment by vrabeshko** [comment]
Wait. Rebuild will not work for now. I created build with version 0.101.5 for now. New version 0.103.2 requires additional libraries to be added. I am wondering of creating layers with diferrent versions in future

**Comment by vrabeshko** [comment]
fixed by building 0.103.5 version
